# Project information
site_name: Mes flashcards
site_url: https://lfavole.github.io/flashcards/

# Repository
repo_name: lfavole/flashcards
repo_url: https://github.com/lfavole/flashcards

theme:
  name: material
  language: fr
  icon:
    logo: material/cards
    repo: fontawesome/brands/github
  custom_dir: overrides

  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - toc.follow

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - privacy
  - search

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
copyright: "Dernière mise à jour : 2024-04-07 12:35:30.606151"
