name: Build the flashcards list

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # at 7:00, 10:00, 13:00, 16:00, 19:00 and 22:00 (no DST = UTC+2)
    - cron: '0 5,8,11,14,17,20 * 4-10 *'
    # same thing during DST (UTC+1)
    - cron: '0 6,9,12,15,18,21 * 1-3,11-12 *'
  workflow_dispatch:
    inputs:
      restoreCollection:
        description: 'Restore collection'
        required: false
        type: boolean

jobs:
  build:
    name: Build the flashcards list
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Restore Anki collection
        uses: actions/cache/restore@v4
        if: ${{ github.event.schedule || inputs.restoreCollection }}
        with:
          path: collection
          key: collection

      - name: Build documentation
        env:
          ANKIWEB_EMAIL: ${{ secrets.ANKIWEB_EMAIL }}
          ANKIWEB_PASSWORD: ${{ secrets.ANKIWEB_PASSWORD }}
        run: |
          python export_and_build_docs.py

      - name: Build the documentation
        run: mkdocs build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Cache Anki collection
        uses: actions/cache/save@v4
        with:
          path: collection
          key: collection

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
